<?xml  version="1.0" encoding="UTF-8"?>

<!DOCTYPE empleados [
<!ELEMENT empleados (empleado*)>
<!ATTLIST empleados total CDATA #REQUIRED>
<!ELEMENT empleado (nombre, apellidos)>
<!ATTLIST empleado id ID #REQUIRED>
<!ATTLIST empleado seccion (desarrollo | sistemas) "sistemas">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
]>

    <empleados>
        <empleado total="100" id="100">
            <seccion>Sistemas</seccion>
            <nombre>Jose Luis</nombre>
            <apellidos> SÃ¡nchez Rodriguez</apellidos>
        </empleado>

    </empleados>
            