=== RestiSanchez/LM-Unidad6/Actividad3/actividad3_4.dtd
<!ELEMENT coleccion (peliculas, actores)>
<!ELEMENT peliculas (pelicula*)>
<!ATTLIST pelicula id ID #REQUIRED>
<!ELEMENT pelicula (#PCDATA)>
<!ELEMENT actores (actor*)>
<!ATTLIST actor peliculas ( p01 | p02 | p03 | p04 | p05 | p06 ) #REQUIRED>
<!ELEMENT actor (#PCDATA)>

=== RestiSanchez/LM-Unidad6/Actividad3/actividad3_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coleccion SYSTEM "actividad3_4.dtd">
<coleccion>
    <peliculas>
    <pelicula id="p01">El Cabo del miedo</pelicula>
    <pelicula id="p02">Casino</pelicula>
    <pelicula id="p03">Infiltrados</pelicula>
    <pelicula id="p04">El Lobo de Wall-Street</pelicula>
    <pelicula id="p05">Lo imposible</pelicula>
    <pelicula id="p06">Avengers: Infinity War</pelicula>
    </peliculas>
    <actores>
    <actor peliculas="p01 p02">Leonardo DiCaprio</actor>
    <actor peliculas="p03 p04">Robert de Niro</actor>
    <actor peliculas="p05 p06">Tom Holland</actor>
    </actores>
    </coleccion>
